---
# aws_rhos_ami: "{{ lookup('ansible.builtin.env', 'RHCOS_AWS_AMI') }}"

# VPC details
VpcCidr: 10.0.0.0/16
AvailabilityZoneCount: 3
SubnetBits: 12

# Cluster network details
cluster_name: "{{ lookup('ansible.builtin.env', 'CLUSTER_NAME') }}"
base_domain: "{{ lookup('ansible.builtin.env', 'BASE_DOMAIN') }}"
cluster_network_cidr: 10.128.0.0/14
cluster_network_hostprefix: 23
machine_network_cidr: 10.0.0.0/16
network_type: OpenShiftSDN
service_network: 172.30.0.0/16
root_volume_iops: 4000
root_volume_size: 500
root_volume_type: io1

# Storage of aws cloudformation templates
cfn_templates_store: aws-cfn-templates


# Cluster Machine details
master_replicas: 1
worker_replicas: 1
hyperthreading: Enabled
master_ec2_instance_type: m4.xlarge
worker_ec2_instance_type: m4.large
aws_machine_arch: arm64

# Root names
vpc: vpc
bastion: bastion
bootstrap: bootstrap
worker: worker-node
master: control-plane
sec_grp: sec
ntwk_and_lbs: network

# Directory where all the action happens. Ensure it is outside this git repository to prevent leackage of secrets or sensitive documents online
install_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}" 

# S3 bucket to store ignition files.
s3_ignition_file_store: "{{ cluster_name }}-infra"