--- 
# - The installation configuration file transforms into the Kubernetes manifests
# - The manifests wrap into the Ignition configuration files.
# - The ignition configuration files are later used to configure the cluster machines.

- name: manifests - Delete any existing manifests created earlier
  command: "rm -rf {{ install_dir }}/openshift && rm -rf {{ install_dir }}/manifests"

- name: manifests - Generate the K8s manifests for the cluster
  command: "openshift-install create manifests --dir {{ install_dir }}/"

# - name: "manifests - Confirm masterSchedulable==false in {{ install_dir }}/manifests/cluster-scheduler-02-config.yml"
#   command: "yq -p yaml -o json {{ install_dir }}/manifests/cluster-scheduler-02-config.yml | jq -c .spec.mastersSchedulable"
#   register: master_schedulable_output
#   # failed_when: master_schedulable_output["stdout"] != false

- name: "manifests - Confirm masterSchedulable==false in {{ install_dir }}/manifests/cluster-scheduler-02-config.yml"
  command: scripts/cluster-scheduler.sh
  debug: script_output

- debug:
    var: script_output

# Remove the Kubernetes manifest files that define the control plane machines & control machine set:
# This is to prevent the cluster from automatically generating control plane machines.

# Remove the Kubernetes manifest files that define the control plane machines
# Remove the Kubernetes manifest files that define the control machine set
# Remove the Kubernetes manifest files that define the worker machine set
- name: manifests - Remove the Kubernetes manifest files 
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ install_dir }}/openshift/99_openshift-cluster-api_master-machines-*.yaml"
    - "{{ install_dir }}/openshift/99_openshift-machine-api_master-control-plane-machine-set.yaml"
    - "{{ install_dir }}/openshift/99_openshift-cluster-api_worker-machineset-*.yaml"