---
- name: "delete-cfn-stack - {{ item }} - Delete CloudFormation Stack"
  cloudformation:
    stack_name: "{{ item }}-cfn-stack"
    state: absent
  register: stack_deletion_result
  ignore_errors: yes
  loop:
    - jump-server 
    - worker-node
    - control-node
    - bootstrap
    - sec
    - network
    - vpc 
        

    # - set_fact:
    #     root_name: worker-node
    
    # - import_tasks: modules/delete-cfn-stack.yml
    
    # - set_fact:
    #     root_name: control-plane

    # - import_tasks: modules/delete-cfn-stack.yml

    # - set_fact:
    #     root_name: bootstrap
    
    # - import_tasks: modules/delete-cfn-stack.yml

    # - set_fact:
    #     root_name: sec
    
    # - import_tasks: modules/delete-cfn-stack.yml

    # - set_fact:
    #     root_name: network
    
    # - import_tasks: modules/delete-cfn-stack.yml

    # - set_fact:
    #     root_name: vpc

    # - import_tasks: modules/delete-cfn-stack.yml

    

    