---
# Extract the installation program & mv execution program to $PATH
- name: "openshift-install - Move {{ downloaded_installer_file }} to {{ artifacts_holder }}"
  copy:
    src: "~/Downloads/{{ downloaded_installer_file }}"
    dest: "{{ artifacts_holder }}"

- name: "openshift-install - Extract the installation program from {{ downloaded_installer_file }} to {{ artifacts_holder }}"
  unarchive:
    src: "{{ artifacts_holder }}/{{ downloaded_installer_file  }}"
    dest: "{{ artifacts_holder }}"

- name: "openshift-install - Copy executible tool to {{ path_dir }} with executable rights"
  copy:
    src: "{{ artifacts_holder }}/openshift-install"
    dest: "{{ path_dir }}"
    mode: '0755'

- name: "openshift-install - Confirm program now available"
  command: "openshift-install version"
  register: confirm_install
  failed_when: confirm_install["failed"] != false
  
# - debug:
#     var: confirm_install

