---
# Creating security groups and roles
- name: sec - Set root name
  set_fact:
    root_name: sec
    stack_to_build: "{{ sec_grp_cfn_stack }}"

- import_tasks: ../../../modules/infra-name.yml

- import_tasks: ../../../modules/hosted-zone.yml

- import_tasks: ../../../modules/vpc-cfn-output.yml

- import_tasks: ../../../modules/ntwk-and-lb-cfn-output.yml

- import_tasks: ../../../modules/build-stack.yml