---
# Playbook to build aws infrastructure and resources
- name: Build aws-infra
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
    
    - import_role:
        name: aws-infra