---
# Build compute plane or worker nodes

- name: Build Compute Plane nodes
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
    
    - import_role:
        name: compute-plane