---
# Playbook for building  aws services
- name: Build Cluster Bootstrap
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
    
    - import_role:
        name: aws-services