---
# Playbook for preparing the manifest and then ignition files
- name: Preparing ignition files
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
    
    - import_role:
        name: ignition-config-files