---
# Playbook for creating install-config.yaml

- name: creating ignition config files
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars

    - import_role:
        name: ignition-config