---
# Playbook to destory build AWS cloudformation stacks
- name: Destroy aws stacks
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars

    # Yes! The length of code can be reduced with a loop! Go ahead and make this better mate!
    - name: "destroy - {{ cluster_name }}-{{ bootstrap }}-stack"
      cloudformation:
        stack_name: "{{ cluster_name }}-{{ bootstrap }}-stack"
        state: absent
      register: stack_deletion_result
      ignore_errors: yes
    
    - name: "destroy - {{ cluster_name }}-{{ worker }}-stack"
      cloudformation:
        stack_name: "{{ cluster_name }}-{{ worker }}-stack"
        state: absent
      register: stack_deletion_result
      ignore_errors: yes
    
    - name: "destroy - {{ cluster_name }}-{{ master }}-stack"
      cloudformation:
        stack_name: "{{ cluster_name }}-{{ master }}-stack"
        state: absent
      register: stack_deletion_result
      ignore_errors: yes

    - name: "destroy - {{ cluster_name }}-{{ sec_grp }}-stack"
      cloudformation:
        stack_name: "{{ cluster_name }}-{{ sec_grp }}-stack"
        state: absent
      register: stack_deletion_result
      ignore_errors: yes

    - name: "destroy - {{ cluster_name }}-{{ lbs_dns }}-stack"
      cloudformation:
        stack_name: "{{ cluster_name }}-{{ lbs_dns }}-stack"
        state: absent
      register: stack_deletion_result
      ignore_errors: yes
    
    # Keeping the VPC around..Not costing much, right? :) 
    
    # - name: "destroy - {{ cluster_name }}-{{ vpc }}-stack"
    #   cloudformation:
    #     stack_name: "{{ cluster_name }}-{{ vpc }}-stack"
    #     state: absent
    #   register: stack_deletion_result
    #   ignore_errors: yes

