---
# Playbook for creating ignition files

- name: creating ignition files
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
    
    - import_role:
        name: aws-creds
        
    - import_role:
        name: ignition