---
# Playbook for creating install-config.yaml

- name: creating install-config.yaml
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars

    - import_role:
        name: install-config