---
# Playbook for building Master Nodes
- name: Build Master nodes
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
      
    - import_role:
        name: control-plane