---
# Playbook for building Security Groups
- name: Build AWS Security Groups
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
      
    - import_role:
        name: sec-grp