---
# Playbook for creating aws creds on the EC2

- name: creating install-config.yaml
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars

    - import_role:
        name: aws-creds