---
# Collect vpc cloudformation stack output

- name: "collect-vpc-into - Get {{ cluster_name }}-vpc-stack CloudFormation stack facts"
  amazon.aws.cloudformation_info:
    stack_name: "{{ cluster_name }}-vpc-stack"
  register: vpc_stack_info

- name: "collect-vpc-into - Set outputs as variables"
  set_fact:
    PrivateSubnetIds: "{{ vpc_.cloudformation[ stack_name ][ 'stack_outputs' ][ 'PrivateSubnetIds' ] }}"
    PublicRouteTableId: "{{ vpc_.cloudformation[ stack_name ][ 'stack_outputs' ][ 'PublicRouteTableId' ] }}"
    PublicSubnetIds: "{{ vpc_.cloudformation[ stack_name ][ 'stack_outputs' ][ 'PublicSubnetIds' ] }}"
    VpcId: "{{ vpc_.cloudformation[ stack_name ][ 'stack_outputs' ][ 'VpcId' ] }}"


    