---
# Collect vpc cloudformation stack output

- name: "vpc-info - Get {{ vpc_cfn_stack }} CloudFormation stack facts"
  amazon.aws.cloudformation_info:
    stack_name: "{{ vpc_cfn_stack }}"
  register: vpc_stack_info

- debug:
    var: vpc_stack_info

- name: "vpc-info - Set outputs as variables"
  set_fact:
    PrivateSubnetIds: "{{ vpc_stack_info.cloudformation[ vpc_cfn_stack ][ 'stack_outputs' ][ 'PrivateSubnetIds' ] }}"
    PublicRouteTableId: "{{ vpc_stack_info.cloudformation[ vpc_cfn_stack ][ 'stack_outputs' ][ 'PublicRouteTableId' ] }}"
    PublicSubnetIds: "{{ vpc_stack_info.cloudformation[ vpc_cfn_stack ][ 'stack_outputs' ][ 'PublicSubnetIds' ] }}"
    VpcId: "{{ vpc_stack_info.cloudformation[ vpc_cfn_stack ][ 'stack_outputs' ][ 'VpcId' ] }}"


    