---
# aws_rhos_ami: "{{ lookup('ansible.builtin.env', 'RHCOS_AWS_AMI') }}"
region: "{{ lookup('ansible.builtin.env', 'REGION') }}"

# VPC details
VpcCidr: 10.0.0.0/16
AvailabilityZoneCount: 3
SubnetBits: 12

# Subnets
# AZ a
az_a_name: "{{ region }}a"
za_public_subnet_cidr: "10.0.1.0/24"
za_private_subnet_cidr: "10.0.11.0/24"

# AZ b
az_b_name: "{{ region }}b"
zb_public_subnet_cidr: "10.0.2.0/24"
zb_private_subnet_cidr: "10.0.12.0/24"


# AZ c
az_c_name: "{{ region }}c"
zc_public_subnet_cidr: "10.0.3.0/24"
zc_private_subnet_cidr: "10.0.13.0/24"

# Cluster network details
cluster_name: "{{ lookup('ansible.builtin.env', 'CLUSTER_NAME') }}"
base_domain: "{{ lookup('ansible.builtin.env', 'BASE_DOMAIN') }}"
cluster_network_cidr: 10.128.0.0/14
cluster_network_hostprefix: 23
machine_network_cidr: 10.0.0.0/16
network_type: OVNKubernetes #networkType OpenShiftSDN is deprecated, please use OVNKubernetes
service_network: 172.30.0.0/16
root_volume_iops: 4000
root_volume_size: 500
root_volume_type: io1

# Storage of aws cloudformation templates
cfn_templates_store: aws-cfn-templates


# AWS AMI
# If you are deploying an OpenShift Container Platform cluster using an 
# AWS Marketplace image, you must first subscribe through AWS. 
# Subscribing to the offer provides you with the AMI ID that the 
# installation program uses to deploy compute nodes.
# https://aws.amazon.com/marketplace/fulfillment?productId=59ead7de-2540-4653-a8b0-fa7926d5c845
# aws_rhos_ami: ami-0fc3a5fb63f4e680b
# Re-using what was used in IPI deployment.
aws_rhos_ami: ami-07013a63289350c3c # AMI NAME : rhcos-415.92.202402130021-0-aarch64


# Cluster Machine details
master_replicas: 3
worker_replicas: 2
hyperthreading: Enabled
ec2_instance_type: m6g.xlarge # Seems like what's available for the region?
aws_machine_arch: x86_64

# Root names
vpc: vpc
bootstrap: bootstrap
worker: worker
master: master
sec_grp: sec
lbs_dns: lb-dns

# Directories
terraform_dir: infra-build
# Directory where all the action happens. Ensure it is outside this git repository to prevent leackage of secrets or sensitive documents online
# If you change this, lots of things could go wrong ;) .. Don't say I didn't warn you!
install_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}" 

# S3 bucket to store ignition files.
s3_ignition_file_store: "{{ cluster_name }}-infra"
