---
# Prepare aws credentials file
- name: write-creds - Check if ~/.aws directory exists
  stat:
    path: "{{ install_dir }}/.aws"
  register: directory_stat

- debug:
    var: directory_stat

- name: write-creds - Create ~/.aws directory to host credentials for aws-cli
  file:
    path: "{{ install_dir }}/.aws"
    state: directory
  when: directory_stat.stat.exists

- name: write-creds - Write on ~/.aws/credentials
  template:
    src: credentials.j2
    dest: "{{ install_dir }}/.aws/credentials"

- name: write-creds - Write on ~/.aws/config
  template:
    src: config.j2
    dest: "{{ install_dir }}/.aws/config"