---
# Collect vpc cloudformation stack details
- name: "sec- - Collect {{ vpc }} stack details"
  set_fact:
    root_name: "{{ vpc }}"

- import_tasks: ../../../modules/obtain-stack-info.yml

# Collect network-and-loadbalancers cloudformation stack details
- name: "sec - Collect {{ ntwk_and_lbs }} stack details"
  set_fact:
    root_name: "{{ ntwk_and_lbs }}"

- import_tasks: ../../../modules/obtain-stack-info.yml

- import_tasks: ../../../modules/infra-name.yml

- import_tasks: ../../../modules/hosted-zone-id.yml

# Creating security groups and roles
- name: sec - Set root name
  set_fact:
    root_name: "{{ sec_grp }}"

- import_tasks: ../../../modules/build-stack.yml
    