---
# Control plane tasks

# Collect vpc cloudformation stack details
- name: "sec- - Collect {{ vpc }} stack details"
  set_fact:
    root_name: "{{ vpc }}"

- import_tasks: ../../../modules/obtain-stack-info.yml

# Collect network-and-loadbalancers cloudformation stack details
- name: "sec - Collect {{ ntwk_and_lbs }} stack details"
  set_fact:
    root_name: "{{ ntwk_and_lbs }}"

- import_tasks: ../../../modules/obtain-stack-info.yml

# Collect sec groups and IAM roles cloudformation stack details
- name: "sec - Collect {{ sec_grp }} stack details"
  set_fact:
    root_name: "{{ sec_grp }}"

- import_tasks: ../../../modules/obtain-stack-info.yml

- import_tasks: ../../../modules/infra-name.yml

- import_tasks: ../../../modules/hosted-zone-id.yml


# You must create the control plane machines in Amazon Web Services (AWS) for your cluster to use. 
- name: control-plane - Set root name
  set_fact:
    root_name: "{{ master }}"
    ign_file: "{{ install_dir }}/master.ign"
    PrivateHostedZoneName: "{{ cluster_name }}.{{ base_domain }}"
    cert_string_file: "{{ install_dir }}/master-ign-cert.txt"
    
- name: "{{ root_name }} - Obtain CertificateAuthorities value from igniition config file"
  shell: "jq -r .ignition.security.tls.certificateAuthorities[0].source {{ ign_file }} > {{ cert_string_file }}"

- name: "{{ root_name }} - Read the string in {{ cert_string_file }} and save it as variable"
  set_fact:
    CertificateAuthorities: "{{ lookup('ansible.builtin.file', '{{ cert_string_file }}') }}"

- import_tasks: ../../../modules/build-stack.yml

- name: "{{ root_name }} - Set outputs as variables"
  set_fact:
    PrivateIPs: "{{ stack_info.cloudformation[ stack_name ][ 'stack_outputs' ][ 'PrivateIPs' ] }}"
