---
# Collect vpc cloudformation stack details
- name: "worker - Collect {{ vpc }} stack info"
  set_fact:
    root_name: "{{ vpc }}"

- import_tasks: ../../../modules/set-vars.yml

# Collect network and load balancers details
- name: "worker - Collect {{ lbs_dns }} stack info"
  set_fact:
    root_name: "{{ lbs_dns }}"

- import_tasks: ../../../modules/set-vars.yml

# Collect sec groups and IAM roles details
- name: "worker - Collect {{ sec_grp }} stack info"
  set_fact:
    root_name: "{{ sec_grp }}"

- import_tasks: ../../../modules/set-vars.yml

# Build Worker Nodes

# The CloudFormation template creates a stack that represents one worker machine. You must create a stack for each worker machine.
# You must create at least two worker machines, so you must create at least two stacks that use this CloudFormation template.

# Build worker
- set_fact:
    root_name: "{{ worker }}"

# Common variables for all worker nodes
- name: worker-node - Set root name and ignition file name
  set_fact:
    ign_file: "{{ install_dir }}/worker.ign"
    cert_string_file: "{{ install_dir }}/worker-ign-cert.txt"
    max_range_value: "{{ worker_replicas + 1 }}"

- name: "{{ root_name }} - Obtain CertificateAuthorities value from igniition config file"
  shell: "jq -r .ignition.security.tls.certificateAuthorities[0].source {{ ign_file }} > {{ cert_string_file }}"

- name: "{{ root_name }} - Read the string in {{ cert_string_file }} and save it as variable"
  set_fact:
    CertificateAuthorities: "{{ lookup('ansible.builtin.file', '{{ cert_string_file }}') }}"
  
# From here, building different worker nodes.
# Yeees! I should this within a loop! But I don't have much time to keep testing that.

- import_tasks: ../../../modules/build-stack.yml