---
# Creating security groups and roles
- name: sec - Set root name
  set_fact:
    root_name: sec
    stack_name: "{{ cluster_name }}-sec-grp-stack"
  
- import_tasks: build-stack.yml

- name: "{{ root_name }} - Set outputs as variables"
  set_fact:
    MasterInstanceProfile: "{{ stack_info.cloudformation[ stack_name ][ 'stack_outputs' ][ 'MasterInstanceProfile' ] }}"
    MasterSecurityGroupId: "{{ stack_info.cloudformation[ stack_name ][ 'stack_outputs' ][ 'MasterSecurityGroupId' ] }}"
    WorkerInstanceProfile: "{{ stack_info.cloudformation[ stack_name ][ 'stack_outputs' ][ 'WorkerInstanceProfile' ] }}"
    WorkerSecurityGroupId: "{{ stack_info.cloudformation[ stack_name ][ 'stack_outputs' ][ 'WorkerSecurityGroupId' ] }}"
    