---
# Build AWS resources
# Collect vpc cloudformation stack details
- name: network - Collect vpc cloudformation stack details
  set_fact:
    root_name: "{{ vpc }}"

- import_tasks: ../../../modules/obtain-stack-info.yml

# Collect infra name
- import_tasks: ../../../modules/infra-name.yml

# Collect hosted zone id value
- import_tasks: ../../../modules/hosted-zone-id.yml

- import_tasks: 1-network.yml
- import_tasks: 2-sec.yml
- import_tasks: 3-bootstrap.yml
- import_tasks: 4-control-plane.yml