---
# Playbook for building VPC

- name: Build AWS VPC
  hosts: localhost
  gather_facts: false

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
    
    - import_role:
        name: vpc