---
- name: "sec- Sleep for 5 minutes for Api Server Dns Name to build in the lb-dns stack"
  wait_for:
    timeout: 300
  delegate_to: localhost


# Collect dns and loadbalancers stack details
- name: sec - Set root name
  set_fact:
    root_name: "{{ lbs_dns }}"

- import_tasks: ../../../modules/obtain-stack-info.yml

# Creating security groups and roles
- name: sec - Set root name
  set_fact:
    root_name: "{{ sec_grp }}"

- import_tasks: ../../../modules/build-stack.yml

